import os
from dotenv import load_dotenv

load_dotenv()

COPART_LOT_IMAGES_URL = os.getenv("COPART_LOT_IMAGES_URL")
COPART_MAIN_URL = os.getenv("COPART_MAIN_URL")
COPART_LOT_URL = os.getenv("COPART_LOT_URL")
BIDCARS_TIPS = os.getenv("BIDCARS_TIPS")

AV_BASE_URL = os.getenv("AV_BASE_URL")

AV_STATISTIC_BASE_URl = os.getenv("AV_STATISTIC_BASE_URl")
AV_STATISTIC_PATH = os.getenv("AV_STATISTIC_PATH")
AV_STATISTIC_BRAND_URl = os.getenv("AV_STATISTIC_BRAND_URl")
AV_STATISTIC_MODEL_URl = os.getenv("AV_STATISTIC_MODEL_URl")
AV_STATISTIC_GENERATION_URl = os.getenv("AV_STATISTIC_GENERATION_URl")
AV_STATISTIC_STATIC_URl = os.getenv("AV_STATISTIC_STATIC_URl")
